# Generated by Django 4.2.4 on 2023-09-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createBy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updateBy',
            field=models.IntegerField(null=True),
        ),
    ]
