# Generated by Django 4.2.4 on 2023-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_product_createby_alter_product_updateby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='createBy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updateBy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
