# Generated by Django 4.2.4 on 2023-09-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_category_createby_alter_category_updateby_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
